name: Deploy to VPS

on:
  push:
    branches: [ production ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            echo "Starting deployment..."
            
            # Create directory if it doesn't exist
            mkdir -p /var/www/twitter-manager
            
            # Navigate to project directory
            cd /var/www/twitter-manager
            
            # Initialize git if needed
            if [ ! -d .git ]; then
              git init
              git remote add origin https://github.com/meetotb/twitter-manager.git
            fi
            
            # Pull latest changes
            echo "Pulling latest changes..."
            git fetch --all
            git checkout production || git checkout -b production
            git reset --hard origin/production
            
            # Install dependencies
            echo "Installing dependencies..."
            npm install --production
            
            # Copy environment file if it doesn't exist
            if [ ! -f .env ]; then
              echo "Creating .env file..."
              echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" > .env
              echo "PORT=3000" >> .env
              echo "ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}" >> .env
            fi
            
            # Install PM2 if needed
            if ! command -v pm2 &> /dev/null; then
              npm install -g pm2
            fi
            
            # Restart PM2
            echo "Restarting application..."
            pm2 restart ecosystem.config.js || pm2 start ecosystem.config.js
            
            echo "Deployment completed successfully!"